### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by xeiona** [viktor-ferenczi/multigrid-projector#42]
How do Install this plugin manually on a nitrado server?

Thanks

Scott

**Comment by viktor-ferenczi** [comment]
In case of 3rd party hosting providers you need to contact their support.
Basically they need to allow the installation of server plugins (DLLs) in some way. 
Alternatively they may provide a curated list of "known good" plugins to choose from.
If they don't support it, then consider changing provider or host the server yourself.
