### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by justryanw** [viktor-ferenczi/multigrid-projector#49]
Tried reinstalling the plugin and on different worlds but I just get the "multiple grids are not supported" when adding the blueprint, other plugins are working fine.

**Comment by viktor-ferenczi** [comment]
Problem could be due to the difference in IL code on Linux.

Does this string present in your log file?

`Refusing to load the plugin due to potentially incompatible code changes`

Also, do you see any log lines with `MultigridProjector` in it, especially the one with `Loading client plugin` ?

**Comment by justryanw** [comment]
I've searched in the most recent few logs and cant find any matches for those :confused:

**Comment by justryanw** [comment]
Ah never mind I was looking in the wrong logs
2023-07-24 13:55:12.829 - Thread:   1 ->  Error: Multigrid Projector: Disabled the plugin due to potentially incompatible code changes in the game or plugin patch collisions. Please report the exception below on the SE Mods Discord (invite is on the Workshop page):; System.NotSupportedException: Refusing to load the plugin due to potentially incompatible code changes in the game:

**Comment by justryanw** [comment]
Here's the full log file
[SpaceEngineers_20230724_135505505.log](https://github.com/viktor-ferenczi/multigrid-projector/files/12148812/SpaceEngineers_20230724_135505505.log)

**Comment by viktor-ferenczi** [comment]
Quoting my March 19 comment from the [releases page](https://github.com/viktor-ferenczi/multigrid-projector/releases):

> Defining the `SE_PLUGIN_DISABLE_METHOD_VERIFICATION` environment variable disables the verification of IL code hash. It is required on Proton.

Please try to define that environment variable and see whether it helps.

**Comment by justryanw** [comment]
Yeah that's done it thank you! Would you consider adding a section to the readme about that environment var being needed on linux?

**Comment by viktor-ferenczi** [comment]
Good idea, added the note on Linux/Wine/Proton to the README.
