### ISSUE TITLE
PCU impact of the projection

### ISSUE THREAD

**Issue by viktor-ferenczi** [viktor-ferenczi/multigrid-projector#60]
Reported by Mike Dude on 2022-05-25:
> I just learned that PCU on a grid increases when a projector is turned on by the amount of blocks in that projection. Is that something that could be countered in the MGP plugin?

- Verify that this indeed happens. 
- Verify on client and Torch.
- If this happens, then evaluate possible config option to affect this.

**Comment by SpaceGT** [comment]
I believe the current behavior is the best way to handle it.
Projections do have a performance hit and ignoring that impact makes it open to abuse.
This can be easily solved by raising the PCU limit.
